### ISSUE TITLE
Stake Bot in the testnet removes the stake from all nodes

### ISSUE THREAD

**Issue by SOFZP** [solana-foundation/stake-o-matic#407]
In the testnet epoch 391, the **stake bot identified all nodes from the delegation program** as violating the conditions according to the metrics. It is based on the results of epoch 389:

https://discord.com/channels/428295358100013066/712904308282097695/1045496460810145814

`Validators by stake level: None=2057, Baseline=5, Bonus=0`
`Non-reporting epochs: "388, 389"`

However, according to https://metrics.solana.com/d/EcFDgFgVk/validator-last-optimistic-slot?orgId=1&refresh=1m for each individual node, you can see that **the metrics are being sent right**.

It is not clear if this is related to the warp jump during the testnet restart, **because we restarted it to epoch 387**, that is, the metrics are considered to be skipped after the warp jump.

**Result: now the bot removes the entire stake from all nodes:**
`Balance: 47726.812844392 SOL`
`Delegated Stake: 47726.810561512 SOL`
`Active Stake: 47726.810561512 SOL`
`Stake deactivates starting from epoch: 391`

**At the moment, there are about 4 hours left until the end of the epoch.**

If do not **stop the deactivation untill end of this epoch**, then this can lead to problems with the testnet (big part of stake deactivates at one moment).

In addition, it is needed to exclude the `None stake` status for all nodes that it was defined by the bot based on the results of epoch 389 and correct it for future epochs.

Otherwise, this may soon lead to deactivations in the mainnet due to violations of the "Testnet Performance >= 5/10" condition.

**Comment by SOFZP** [comment]
Hello, on the Foundation website and in the API of the bot, there were marks about the `None stake` in the 389th epoch:
https://kyc-api.vercel.app/api/validators/details?pk=ANY_TESTNET_PUBLIC_KEY&epoch=389
`"state":"None"`
`"state_reason":"Only reported correctly in 7/9 epochs. Non-reporting epochs: \"388, 389\""`
`"self_reported_metrics":{"pass":false,"reason":"No report from validator for epoch 389"}`
`self_reported_metrics_summary":{"pass":false,"reason":"Only reported correctly in 7/9 epochs. Non-reporting epochs: \"388, 389\""}}`

![image](https://user-images.githubusercontent.com/80635831/205043162-01fa994a-0070-4cc0-8a9c-9599642e6b61.png)


The **Testnet Performance**, which is important criteria for the mainnet, has already **fall to 6/10** here:
https://kyc-api.vercel.app/api/validators/list?offset=0&limit=15&order_by=name&order=asc&search_term=ANY_TESTNET_PUBLIC_KEY
`"tn_calculated_stats": ........ "num_bonus_last_10":6`
But is normal at the website:

![image](https://user-images.githubusercontent.com/80635831/205042217-6a3dfbde-3aa9-4d63-849e-587020d01601.png)


For the nodes that were on Hetzner at the time of the its fall, situation is **Current Testnet Performance: 5/10** here:
https://kyc-api.vercel.app/api/validators/list?offset=0&limit=15&order_by=name&order=asc&search_term=FORMER_HETZNER_TESTNET_PUBLIC_KEY
`"num_bonus_last_10":5`
(but 8/10 on the website, so cannot understand where is relevant info for the stakebot)


**And now, at the moment, metrics are not transmitted at all (both tesnet and mainnet).**

It can be seen here:
https://metrics.solana.com/d/EcFDgFgVk/validator-last-optimistic-slot?orgId=1&refresh=1m&from=now-12h&to=now&var-bucket=mainnet-beta


I checked a dozen nodes - problem is not private, it is general.

**My concern is that after the "Testnet Performance >= 5/10" condition, the mainnet nodes de-stakes will start.**, but it is not clear where stakebot will check data, at kyc-api.vercel.app/api/validators or not.

**Comment by danpaul000** [comment]
@c3pko @alex-at-planetariummusic we had to manually override the testnet bot last epoch to bypass the bug.  Once it is fixed correctly, we should make sure people are not incorrectly marked in the historical database, so they are not punished for lack of metrics in the future against the bad epoch.
