### ISSUE TITLE
The mainnet staking bot is removing validators from the delegation program due to incorrect commission  change detection in validators.app.

### ISSUE THREAD

**Issue by Pervezhans** [solana-foundation/stake-o-matic#443]
The site validators.app identified a huge number of validators changing fees at the same time at the border of epochs 403 and 404, when in reality this did not happen. As a result, the mainnet staking bot, based on this information, removed these validators from the delegation program.
Third party commission  change detection sites such as https://stakewiz.com or https://validators-api.marinade.finance/reports/commission-changes did not capture commission changes.
https://www.validators.app/commission-changes?locale=en&network=mainnet
A few examples besides dozens of others.

CXASPwmruKhiL4eRWEREYktgQHvTMJcXVFwRgXRaswe9
https://www.validators.app/validators/CXASPwmruKhiL4eRWEREYktgQHvTMJcXVFwRgXRaswe9?network=mainnet
https://solana.org/sfdp-validators/CXASPwmruKhiL4eRWEREYktgQHvTMJcXVFwRgXRaswe9
https://stakewiz.com/validator/BGFALjMdG8x4Vzwh5H1q61HWZagMXEk2wkFMteH5qcNk

GezZ48oKmb79E9V4ouz53eNVifLGz8QqabVuVVJdvWqk
https://www.validators.app/validators/GezZ48oKmb79E9V4ouz53eNVifLGz8QqabVuVVJdvWqk?network=mainnet
https://solana.org/sfdp-validators/GezZ48oKmb79E9V4ouz53eNVifLGz8QqabVuVVJdvWqk
https://stakewiz.com/validator/7oRCGUVzrprUqt9HqMuiSDMDhyN4proYsSGSLiFjHme2

8LVVWgBvrRaAmcRB8BQ77BNe8YEqZ3zydMHhUYXx1bV
https://www.validators.app/validators/8LVVWgBvrRaAmcRB8BQ77BNe8YEqZ3zydMHhUYXx1bV?network=mainnet
https://solana.org/sfdp-validators/8LVVWgBvrRaAmcRB8BQ77BNe8YEqZ3zydMHhUYXx1bV
https://stakewiz.com/validator/ADepVu5y5n4uF5zcuFpccbY4FWa5XY5RWMViGXNeC8gb

CTwsruptUccEtZGNxBDbuusHYxkBX3P6ndrxVjSG213y
https://www.validators.app/validators/CTwsruptUccEtZGNxBDbuusHYxkBX3P6ndrxVjSG213y?network=mainnet
https://solana.org/sfdp-validators/CTwsruptUccEtZGNxBDbuusHYxkBX3P6ndrxVjSG213y
https://stakewiz.com/validator/Fhks5gukimP6vxKYbRY4V1aw888EgHhpdDSscD9V6bub

ESihGHvvNWPBTu3RZohRgEEuBmoyVhgHYTf3Cot9523L
https://www.validators.app/validators/ESihGHvvNWPBTu3RZohRgEEuBmoyVhgHYTf3Cot9523L?locale=en&network=mainnet&order=stake&refresh=
https://solana.org/sfdp-validators/ESihGHvvNWPBTu3RZohRgEEuBmoyVhgHYTf3Cot9523L
https://stakewiz.com/validator/HtRAGpko23W2t8wPUU8HuUQC1TrRUuK64K8RCqRD5ubX

**Comment by tigarcia** [comment]
This has been resolved. We have a task for changing how we check commission changes.
